services:
  meet-app-postgresql:
    image: 'postgres:latest'
    ports:
     - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meetapp
  meet-app-redis:
    image: redis:latest
    ports:
     - 6379:6379
